# Generated by Django 5.0.6 on 2024-06-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('security_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=150)),
                ('strategy', models.CharField(choices=[('Active Short', 'Active Short'), ('RelVal', 'RelVal'), ('SLBs', 'SLBs'), ('Curves', 'Curves'), ('Use of proceeds', 'Use of proceeds'), ('Hedge', 'Hedge')], max_length=50)),
                ('strategy_id', models.CharField(max_length=100)),
                ('instrument_type', models.CharField(choices=[('Bonds', 'Bonds'), ('CDS', 'CDS'), ('Futures', 'Futures'), ('FX', 'FX')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spread', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direction', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=4)),
                ('no_of_contracts', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
