# Generated by Django 5.0.6 on 2024-06-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='direction',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='trade',
            name='instrument_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trade',
            name='strategy',
            field=models.CharField(max_length=50),
        ),
    ]
