# Generated by Django 5.0.6 on 2024-06-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_remove_trade_strategy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='instrument_type',
            field=models.CharField(choices=[('bonds', 'Bonds'), ('cds', 'CDS'), ('futures', 'Futures'), ('fx', 'FX')], max_length=50),
        ),
    ]
