# Generated by Django 5.0.6 on 2024-06-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_alter_trade_instrument_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='strategy',
            field=models.CharField(choices=[('Active Short', 'Active Short'), ('RelVal', 'RelVal'), ('SLBs', 'SLBs'), ('Curves', 'Curves'), ('Use of proceeds', 'Use of proceeds'), ('Hedge', 'Hedge')], max_length=50),
        ),
    ]
