# Generated by Django 5.0.6 on 2024-06-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_trade_trade_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
